modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="mycommands" #mandatory
version="${file.jarVersion}" #mandatory
displayName="My Commands" #mandatory
logoFile="mycommands.png" #optional
credits="" #optional
authors="GhxstSparky" #optional
description='''
Mod that adds some useful commands.
'''
[[dependencies.mycommands]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.mycommands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
